# pyproject.toml

[build-system]
requires = ["setuptools>=46.1.0", "wheel>=0.36.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
setup-hooks = ["studip_cli.setup_hooks.get_requires_for_build_sdist"]
